services:
  spring-app:
    image: lexilearn-spring-boot-main
    container_name: lexilearn-spring-boot-main-container
    network_mode: host

    ports:
      - '5001:5001'
    environment:
      PORT: ${PORT}
      API_KEY: ${API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JAVA_ENV: ${JAVA_ENV}
      PRIVATE_KEY: ${PRIVATE_KEY}
      PRIVATE_TIME: ${PRIVATE_TIME}
      PUBLIC_KEY: ${PUBLIC_KEY}
      PUBLIC_TIME: ${PUBLIC_TIME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER_NAME: ${MAIL_USER_NAME}
      MAIL_USER_PASSWORD: ${MAIL_USER_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FRONT_END_CLIENT_SERVER: ${FRONT_END_CLIENT_SERVER}
      API_GATEWAY_SERVER: ${API_GATEWAY_SERVER}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      MEDIA_SERVER_URL: ${MEDIA_SERVER_URL}
      MEDIA_SERVER_API_KEY: ${MEDIA_SERVER_API_KEY}
      ACCESS_TOKEN_PRIVATE_KEY: ${ACCESS_TOKEN_PRIVATE_KEY}
      ACCESS_TOKEN_PUBLIC_KEY: ${ACCESS_TOKEN_PUBLIC_KEY}
      ACCESS_TOKEN_DURATION: ${ACCESS_TOKEN_DURATION}
      REFRESH_TOKEN_PRIVATE_KEY: ${REFRESH_TOKEN_PRIVATE_KEY}
      REFRESH_TOKEN_PUBLIC_KEY: ${REFRESH_TOKEN_PUBLIC_KEY}
      REFRESH_TOKEN_DURATION: ${REFRESH_TOKEN_DURATION}
